// Comprehensive NSE universe provided by user (Nifty 100/200 + Smallcap focus)
// All symbols without .NS suffix. Backend adds .NS for Yahoo and fetches real names via quote.

export interface StockMeta {
  symbol: string;
  name: string;
}

// Combined and deduplicated list (approx 250+ liquid NSE stocks)
const rawSymbols = [
  // From first list (larger caps / midcaps)
  "360ONE", "3MINDIA", "ACC", "AIAENG", "APLAPOLLO", "AUBANK", "AWL", "ABBOTINDIA", "ATGL", "ABCAPITAL",
  "AJANTPHARM", "ALKEM", "APARINDS", "APOLLOTYRE", "ASHOKLEY", "ASTRAL", "AUROPHARMA", "BSE", "BALKRISIND", "BANKINDIA",
  "MAHABANK", "BERGEPAINT", "BDL", "BHARATFORG", "BHEL", "BHARTIHEXA", "BIOCON", "BLUESTARCO", "CRISIL", "COCHINSHIP",
  "COFORGE", "COLPAL", "CONCOR", "COROMANDEL", "CUMMINSIND", "DABUR", "DALBHARAT", "DEEPAKNTR", "DIXON", "ENDURANCE",
  "ESCORTS", "EXIDEIND", "NYKAA", "FEDERALBNK", "FACT", "FORTIS", "GMRAIRPORT", "GICRE", "GLAXO",
  "GLENMARK", "MEDANTA", "GODFRYPHLP", "GODREJIND", "GODREJPROP", "FLUOROCHEM", "GUJGASLTD", "HDFCAMC", "HEROMOTOCO", "HEXT",
  "HINDPETRO", "POWERINDIA", "HONAUT", "HUDCO", "ICICIPRULI", "IDBI", "IDFCFIRSTB", "IRB", "ITCHOTELS", "INDIANB",
  "IOB", "IRCTC", "IREDA", "IGL", "INDUSTOWER", "INDUSINDBK", "IPCALAB", "JKCEMENT", "JSWINFRA", "JSL",
  "JUBLFOOD", "KPRMILL", "KEI", "KPITTECH", "KALYANKJIL", "LTF", "LTTS", "LICHSGFIN", "LINDEINDIA", "LLOYDSME",
  "LUPIN", "MRF", "M&MFIN", "MANKIND", "MARICO", "MFSL", "MOTILALOFS", "MPHASIS", "MUTHOOTFIN", "NHPC",
  "NLCINDIA", "NMDC", "NTPCGREEN", "NATIONALUM", "NAM-INDIA", "OBEROIRLTY", "OIL", "PAYTM", "OFSS", "POLICYBZR",
  "PIIND", "PAGEIND", "PATANJALI", "PERSISTENT", "PETRONET", "PHOENIXLTD", "POLYCAB", "PREMIERENE", "PRESTIGE", "PGHH",
  "RVNL", "SBICARD", "SJVN", "SRF", "SCHAEFFLER", "SONACOMS", "SAIL", "SUNDARMFIN", "SUPREMEIND", "SUZLON",
  "SWIGGY", "SYNGENE", "TATACOMM", "TATAELXSI", "TATAINVEST", "TATATECH", "NIACL", "THERMAX", "TORNTPOWER", "TIINDIA",
  "UCOBANK", "UNOMINDA", "UPL", "UNIONBANK", "UBL", "VMM", "IDEA", "VOLTAS", "WAAREEENER", "YESBANK",

  // From NIFTY_SMALLCAP_SYMBOLS list
  "ACMESOLAR", "AADHARHFC", "AARTIIND", "AAVAS", "ACE", "ABFRL", "ABLBL", "ABREL", "ABSLAMC", "AEGISLOG",
  "AEGISVOPAK", "AFCONS", "AFFLE", "AKUMS", "AKZOINDIA", "APLLTD", "ALKYLAMINE", "ALOKINDS", "ARE&M", "AMBER",
  "ANANDRATHI", "ANANTRAJ", "ANGELONE", "APTUS", "ASAHIINDIA", "ASTERDM", "ASTRAZEN", "ATHERENERG", "ATUL", "AIIL",
  "BASF", "BEML", "BLS", "BALRAMCHIN", "BANDHANBNK", "BATAINDIA", "BAYERCROP", "BIKAJI", "BSOFT", "BLUEDART",
  "BLUEJET", "BBTC", "FIRSTCRY", "BRIGADE", "MAPMYINDIA", "CCL", "CESC", "CAMPUS", "CANFINHOME", "CAPLIPOINT",
  "CGCL", "CARBORUNIV", "CASTROLIND", "CEATLTD", "CENTRALBK", "CDSL", "CENTURYPLY", "CERA", "CHALET", "CHAMBLFERT",
  "CHENNPETRO", "CHOICEIN", "CHOLAHLDNG", "CUB", "CLEAN", "COHANCE", "CAMS", "CONCORDBIO", "CRAFTSMAN", "CREDITACC",
  "CROMPTON", "CYIENT", "DCMSHRIRAM", "DOMS", "DATAPATTNS", "DEEPAKFERT", "DELHIVERY", "DEVYANI", "AGARWALEYE", "LALPATHLAB",
  "EIDPARRY", "EIHOTEL", "ELECON", "ELGIEQUIP", "EMAMILTD", "EMCURE", "ENGINERSIN", "ERIS", "FINCABLES", "FINPIPE",
  "FSL", "FIVESTAR", "FORCEMOT", "GRSE", "GILLETTE", "GLAND", "GODIGIT", "GPIL", "GODREJAGRO", "GRANULES",
  "GRAPHITE", "GRAVITA", "GESHIP", "GMDCLTD", "GSPL", "HEG", "HBLENGINE", "HFCL", "HAPPSTMNDS", "HSCL",
  "HINDCOPPER", "HOMEFIRST", "HONASA", "IFCI", "IIFL", "INOXINDIA", "IRCON", "ITI", "INDGN", "INDIACEM",
  "INDIAMART", "IEX", "INOXWIND", "INTELLECT", "IGIL", "IKS", "JBCHEPHARM", "JBMA", "JKTYRE", "JMFINANCIL",
  "JSWCEMENT", "JPPOWER", "J&KBANK", "JINDALSAW", "JUBLINGREA", "JUBLPHARMA", "JWL", "JYOTHYLAB", "JYOTICNC", "KSB",
  "KAJARIACER", "KPIL", "KARURVYSYA", "KAYNES", "KEC", "KFINTECH", "KIRLOSBROS", "KIRLOSENG", "KIMS", "LTFOODS",
  "LATENTVIEW", "LAURUSLABS", "THELEELA", "LEMONTREE", "MMTC", "MGL", "MAHSCOOTER", "MAHSEAMLES", "MANAPPURAM", "MRPL",
  "METROPOLIS", "MINDACORP", "MSUMI", "MCX", "NATCOPHARM", "NBCC", "NCC", "NSLNISP", "NH", "NAVA",
  "NAVINFLUOR", "NETWEB", "NEULANDLAB", "NEWGEN", "NIVABUPA", "NUVAMA", "NUVOCO", "OLAELEC", "OLECTRA", "ONESOURCE",
  "PCBL", "PGEL", "PNBHOUSING", "PTCIL", "PVRINOX", "PFIZER", "PPLPHARMA", "POLYMED", "POONAWALLA", "PRAJIND",
  "RRKABEL", "RBLBANK", "RHIM", "RITES", "RADICO", "RAILTEL", "RAINBOW", "RKFORGE", "RCF", "REDINGTON",
  "RELINFRA", "RPOWER", "SBFC", "SAGILITY", "SAILIFE", "SAMMAANCAP", "SAPPHIRE", "SARDAEN", "SAREGAMA", "SCHNEIDER",
  "SCI", "SHYAMMETL", "SIGNATURE", "SOBHA", "SONATSOFTW", "STARHEALTH", "SUMICHEM", "SUNTV", "SUNDRMFAST", "SWANCORP",
  "SYRMA", "TBOTEK", "TATACHEM", "TTML", "TECHNOE", "TEJASNET", "RAMCOCEM", "TIMKEN", "TITAGARH", "TARIL",
  "TRIDENT", "TRIVENI", "TRITURBINE", "UTIAMC", "USHAMART", "VGUARD", "DBREALTY", "VTL", "MANYAVAR", "VENTIVE",
  "VIJAYA", "WELCORP", "WELSPUNLIV", "WHIRLPOOL", "WOCKPHARMA", "ZFCVINDIA", "ZEEL", "ZENTEC", "ZENSARTECH", "ECLERX"
];

// Deduplicate while preserving order
const unique = Array.from(new Set(rawSymbols));

export const NSE_UNIVERSE: StockMeta[] = unique.map(sym => ({
  symbol: sym,
  name: sym, // Will be replaced by real shortName from Yahoo quote during scan
}));

// Helper to get full Yahoo symbol
export function toYahooSymbol(sym: string): string {
  return sym.endsWith(".NS") ? sym : `${sym}.NS`;
}

// For display
export function shortSymbol(sym: string): string {
  return sym.replace(".NS", "");
}
